=== shrinktofit/cocos4/cc.config.schema.json
{
  "$ref": "#/definitions/Config",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Config": {
      "additionalProperties": false,
      "properties": {
        "constants": {
          "$ref": "#/definitions/IConstantConfig",
          "description": "The constants config for engine and user."
        },
        "features": {
          "additionalProperties": {
            "$ref": "#/definitions/Feature"
          },
          "description": "Engine features. Keys are feature IDs.",
          "type": "object"
        },
        "includes": {
          "description": "Included files for quick-compiler.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "index": {
          "$ref": "#/definitions/IndexConfig",
          "description": "Describe how to generate the index module `'cc'`. Currently not used."
        },
        "moduleOverrides": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "isVirtualModule": {
                "type": "boolean"
              },
              "overrides": {
                "additionalProperties": {
                  "type": "string"
                },
                "type": "object"
              },
              "test": {
                "$ref": "#/definitions/Test"
              }
            },
            "required": [
              "test",
              "overrides",
              "isVirtualModule"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "optimizeDecorators": {
          "$ref": "#/definitions/IOptimizeDecorators",
          "description": "The decorators to be optimize when build engine."
        },
        "treeShake": {
          "$ref": "#/definitions/ITreeShakeConfig",
          "description": "The TreeShake config"
        }
      },
      "required": [
        "features",
        "includes",
        "constants",
        "optimizeDecorators"
      ],
      "type": "object"
    },
    "ConstantTypeName": {
      "enum": [
        "boolean",
        "number"
      ],
      "type": "string"
    },
    "Feature": {
      "additionalProperties": false,
      "description": "An engine feature.",
      "properties": {
        "dependentAssets": {
          "description": "List of uuid that the feature depends on.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "dependentModules": {
          "description": "List of module that the feature depends on.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "dependentScripts": {
          "description": "List of script uuid that the feature depends on.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "intrinsicFlags": {
          "additionalProperties": {},
          "description": "Flags to set when this feature is enabled.",
          "type": "object"
        },
        "isNativeOnly": {
          "default": false,
          "description": "Whether it is a native only feature, default is false.",
          "type": "boolean"
        },
        "modules": {
          "description": "Modules to be included in this feature in their IDs. The ID of a module is its relative path(no extension) under /exports/.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "overrideConstants": {
          "additionalProperties": {
            "type": [
              "number",
              "boolean"
            ]
          },
          "description": "Constants to override when this feature is enabled. The overridden constants should be defined in cc.config.json.",
          "type": "object"
        }
      },
      "required": [
        "modules"
      ],
      "type": "object"
    },
    "IConstantConfig": {
      "additionalProperties": {
        "$ref": "#/definitions/IConstantInfo"
      },
      "type": "object"
    },
    "IConstantInfo": {
      "additionalProperties": false,
      "properties": {
        "ccGlobal": {
          "default": false,
          "description": "Whether exported to global as a `CC_XXXX` constant. eg. WECHAT is exported to global.CC_WECHAT NOTE: this is a feature of compatibility with Cocos 2.x engine. Default is false.",
          "type": "boolean"
        },
        "comment": {
          "description": "The comment of the constant. Which is used to generate the consts.d.ts file.",
          "type": "string"
        },
        "dynamic": {
          "default": false,
          "description": "Some constant can't specify the value in the Editor, Preview or Test environment, so we need to dynamically judge them in runtime. These values are specified in a helper called `helper-dynamic-constants.ts`. Default is false.",
          "type": "boolean"
        },
        "internal": {
          "description": "Whether exported to developer. If true, it's only exported to engine.",
          "type": "boolean"
        },
        "type": {
          "$ref": "#/definitions/ConstantTypeName",
          "description": "The type of the constant for generating consts.d.ts file."
        },
        "value": {
          "description": "The default value of the constant. It can be a boolean, number or string. When it's a string type, the value is the result of eval().",
          "type": [
            "boolean",
            "string",
            "number"
          ]
        },
        "xBuild": {
          "$ref": "#/definitions/XBuildConstantInfo",
          "description": "x-build specific options for dynamic constant generation."
        }
      },
      "required": [
        "comment",
        "type",
        "value",
        "internal"
      ],
      "type": "object"
    },
    "XBuildConstantInfo": {
      "additionalProperties": false,
      "properties": {
        "category": {
          "description": "A category marker for constants that share x-build configuration behavior.",
          "type": "string"
        },
        "configurable": {
          "description": "Whether x-build exposes this constant through the runtime configuration store.",
          "type": "boolean"
        },
        "dynamic": {
          "description": "Whether x-build emits this constant from a dynamic helper instead of the generated constants loop.",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "IOptimizeDecorators": {
      "additionalProperties": false,
      "properties": {
        "editorDecorators": {
          "description": "The decorators which should be removed directly when they only work in Cocos Creator editor.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "fieldDecorators": {
          "description": "The decorators which should be optimized when they only decorate class fields.",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "required": [
        "fieldDecorators",
        "editorDecorators"
      ],
      "type": "object"
    },
    "ITreeShakeConfig": {
      "additionalProperties": false,
      "properties": {
        "noSideEffectFiles": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "required": [
        "noSideEffectFiles"
      ],
      "type": "object"
    },
    "IndexConfig": {
      "additionalProperties": false,
      "properties": {
        "modules": {
          "additionalProperties": {
            "additionalProperties": false,
            "properties": {
              "deprecated": {
                "description": "If `true`, accesses the exports of this module from `'cc'` will be marked as deprecated.",
                "type": "boolean"
              },
              "ns": {
                "description": "If specified, export contents of the module into a namespace specified by `ns` and then export that namespace into `'cc'`. If not specified, contents of the module will be directly exported into `'cc'`.",
                "type": "string"
              }
            },
            "type": "object"
          },
          "type": "object"
        }
      },
      "type": "object"
    },
    "Test": {
      "type": "string"
    }
  }
}

=== shrinktofit/cocos4/cc.config.json
{
    "$schema": "./cc.config.schema.json",
    "features": {
        "base": {
            "modules": [
                "base"
            ],
            "dependentAssets": [
                "970b0598-bcb0-4714-91fb-2e81440dccd8",
                "bcd64cc6-2dd9-43f6-abbe-66318d332032",
                "d930590d-bb92-4cc8-8bd1-23cd027f9edf",
                "a3cd009f-0ab0-420d-9278-b9fdab939bbc"
            ]
        },
        "gfx-webgl": {
            "modules": [
                "gfx-webgl"
            ]
        },
        "gfx-webgl2": {
            "modules": [
                "gfx-webgl2"
            ]
        },
        "gfx-empty": {
            "modules": [
                "gfx-empty"
            ]
        },
        "gfx-webgpu": {
            "modules": [
                "gfx-webgpu"
            ]
        },
        "3d": {
            "modules": [
                "3d"
            ],
            "overrideConstants": {
                "USE_3D": true
            },
            "dependentAssets": [
                "511d2633-09a7-4bdd-ac42-f778032124b3",
                "5d45aa00-e064-4938-b314-4265f0c2258c",
                "9361fd90-ba52-4f84-aa93-6e878fd576ca"
            ]
        },
        "animation": {
            "modules": [
                "animation"
            ]
        },
        "skeletal-animation": {
            "modules": [
                "animation",
                "skeletal-animation"
            ]
        },
        "2d": {
            "modules": [
                "2d",
                "sorting"
            ],
            "dependentAssets": [
                "60f7195c-ec2a-45eb-ba94-8955f60e81d0",
                "1c02ae6f-4492-4915-b8f8-7492a3b1e4cd",
                "810e96e4-e456-4468-9b59-f4e8f39732c0",
                "efe8e2a3-eace-427b-b4f1-cb8a937ec77d",
                "e9aa9a3e-5b2b-4ac7-a2c7-073de2b2b24f",
                "8bbdbcdd-5cd4-4100-b6d5-b7c9625b6107",
                "50f4348b-c883-4e2f-8f11-ce233b859fa1",
                "fda095cb-831d-4601-ad94-846013963de8",
                "f92806d7-1768-443f-afe8-12bcde84d0f0",
                "dd3a144d-ab7f-41f0-82b8-2e43a090d496",
                "f0416e68-0200-4b77-a926-4f9d16e494da"
            ]
        },
        "rich-text": {
            "modules": [
                "rich-text"
            ],
            "dependentModules": [
                "2d"
            ]
        },
        "mask": {
            "modules": [
                "mask"
            ],
            "dependentModules": [
                "2d"
            ]
        },
        "graphics": {
            "modules": [
                "graphics"
            ],
            "dependentModules": [
                "2d"
            ]
        },
        "ui-skew": {
            "modules": [
                "ui-skew"
            ],
            "overrideConstants": {
                "USE_UI_SKEW": true
            },
            "dependentModules": [
                "2d"
            ]
        },
        "ui": {
            "modules": [
                "ui",
                "2d"
            ]
        },
        "affine-transform": {
            "modules": [
                "affine-transform"
            ]
        },
        "sorting-2d": {
            "modules": [
                "sorting-2d"
            ],
            "overrideConstants": {
                "USE_SORTING_2D": true
            },
            "dependentModules": [
                "2d"
            ]
        },
        "particle": {
            "modules": [
                "particle"
            ],
            "dependentAssets": [
                "d1346436-ac96-4271-b863-1f4fdead95b0",
                "971bdb23-3ff6-43eb-b422-1c30165a3663",
                "17debcc3-0a6b-4b8a-b00b-dc58b885581e",
                "711ebe11-f673-4cd9-9a83-63c60ba54c5b",
                "c0143906-9aed-447e-9436-2ae8512d1b6e",
                "14da1725-c4c2-42b4-ab08-ee0aeb6898b3",
                "081cab31-dccd-428e-8652-f2404cc81c47",
                "78e0584a-4343-4727-8f37-e14e65c2a2db"
            ]
        },
        "particle-2d": {
            "modules": [
                "particle-2d"
            ],
            "dependentModules": [
                "2d"
            ]
        },
        "physics-framework": {
            "modules": [
                "physics-framework"
            ]
        },
        "physics-cannon": {
            "modules": [
                "physics-cannon",
                "physics-framework"
            ],
            "dependentAssets": [
                "ba21476f-2866-4f81-9c4d-6e359316e448"
            ]
        },
        "physics-physx": {
            "modules": [
                "physics-physx",
                "physics-framework"
            ],
            "dependentAssets": [
                "ba21476f-2866-4f81-9c4d-6e359316e448"
            ]
        },
        "physics-ammo": {
            "modules": [
                "physics-ammo",
                "physics-framework"
            ],
            "dependentAssets": [
                "ba21476f-2866-4f81-9c4d-6e359316e448"
            ]
        },
        "physics-builtin": {
            "modules": [
                "physics-builtin",
                "physics-framework"
            ],
            "dependentAssets": [
                "ba21476f-2866-4f81-9c4d-6e359316e448"
            ]
        },
        "physics-2d-framework": {
            "modules": [
                "physics-2d-framework"
            ]
        },
        "physics-2d-box2d-jsb": {
            "modules": [
                "physics-2d-box2d-jsb",
                "physics-2d-framework"
            ]
        },
        "physics-2d-box2d": {
            "modules": [
                "physics-2d-box2d",
                "physics-2d-framework"
            ]
        },
        "physics-2d-builtin": {
            "modules": [
                "physics-2d-builtin",
                "physics-2d-framework"
            ]
        },
        "physics-2d-box2d-wasm": {
            "modules": [
                "physics-2d-box2d-wasm",
                "physics-2d-framework"
            ]
        },
        "intersection-2d": {
            "modules": [
                "intersection-2d"
            ]
        },
        "primitive": {
            "modules": [
                "primitive"
            ]
        },
        "profiler": {
            "modules": [
                "profiler"
            ],
            "dependentAssets": [
                "871c3b6c-7379-419d-bda3-794b239ab90d"
            ]
        },
        "occlusion-query": {
            "modules": [],
            "dependentAssets": [
                "d9937e59-61fe-4ec6-92ab-7ac5a19c89b0"
            ]
        },
        "geometry-renderer": {
            "modules": [
                "geometry-renderer"
            ],
            "dependentAssets": [
                "4bb480dd-8384-4bc9-987f-de67cc53052a"
            ]
        },
        "debug-renderer": {
            "modules": [],
            "dependentAssets": [
                "ff9be190-20a4-4e48-b68c-76e3c7cff085",
                "0835f102-5471-47a3-9a76-01c07ac9cdb2",
                "b5475517-23b9-4873-bc1a-968d96616081",
                "0ed97c56-390e-4dd1-96b7-e7f2d93a98ed",
                "b23391b6-52eb-46a6-8da1-6244d9d315fb"
            ]
        },
        "audio": {
            "modules": [
                "audio"
            ]
        },
        "video": {
            "modules": [
                "video"
            ]
        },
        "xr": {
            "modules": [
                "xr"
            ],
            "overrideConstants": {
                "USE_XR": true
            }
        },
        "light-probe": {
            "modules": [
                "light-probe"
            ]
        },
        "terrain": {
            "modules": [
                "terrain"
            ],
            "dependentAssets": [
                "1d08ef62-a503-4ce2-8b9a-46c90873f7d3"
            ]
        },
        "webview": {
            "modules": [
                "webview"
            ]
        },
        "tween": {
            "modules": [
                "tween"
            ]
        },
        "tiled-map": {
            "modules": [
                "tiled-map"
            ],
            "dependentModules": [
                "2d"
            ]
        },
        "vendor-google": {
            "modules": [
                "vendor-google"
            ],
            "intrinsicFlags": {
                "USE_VENDOR_GOOGLE": true
            }
        },
        "spine-3.8": {
            "modules": [
                "spine"
            ],
            "dependentAssets": [
                "c27215d8-6835-4b68-bfbb-bdeac6100c04",
                "b5d6115f-0370-4d7c-aad3-c194cc71cf98"
            ],
            "dependentModules": [
                "2d"
            ],
            "intrinsicFlags": {
                "SPINE_3_8": true
            }
        },
        "spine-4.2": {
            "modules": [
                "spine"
            ],
            "dependentAssets": [
                "c27215d8-6835-4b68-bfbb-bdeac6100c04",
                "b5d6115f-0370-4d7c-aad3-c194cc71cf98"
            ],
            "dependentModules": [
                "2d"
            ],
            "intrinsicFlags": {
                "SPINE_4_2": true
            }
        },
        "dragon-bones": {
            "modules": [
                "dragon-bones"
            ],
            "dependentAssets": [
                "c27215d8-6835-4b68-bfbb-bdeac6100c04",
                "b5d6115f-0370-4d7c-aad3-c194cc71cf98"
            ],
            "dependentModules": [
                "2d"
            ]
        },
        "marionette": {
            "modules": [],
            "intrinsicFlags": {
                "MARIONETTE": true
            }
        },
        "procedural-animation": {
            "modules": [],
            "intrinsicFlags": {
                "PROCEDURAL_ANIMATION": true
            }
